name: Build Executable

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install PyInstaller PySide6

      # Step 4: Convert .ui files to .py (if needed)
      - name: Convert .ui files to .py
        run: |
          for /r %f in (*.ui) do pyside6-uic %f -o %~dpnf.py

      # Step 5: Build the executable
      - name: Build executable
        run: |
          pyinstaller --onefile --noconsole --name PythonDatabase-main gui.py

      # Step 6: Upload the executable as an artifact
      - name: Upload executable
        uses: actions/upload-artifact@v3
        with:
          name: PythonDatabase-main-exe
          path: dist/PythonDatabase-main.exe
